version: '3.7'

services:

    http:
        container_name: microservice_http
        image: nginx:latest
        restart: always
        ports:
            - "8007:80"
            - "447:443"
        volumes:
            - ./public:/var/www/html/public
            - ./.docker/dev/microservice_http/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/dev/microservice_http/nginx/log:/var/log/nginx
        networks:
            - microservice_network

    api:
        container_name: microservice_api
        image: marcelofabianov/php-8.1-fpm-oci
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "9007:9000"
        networks:
            - microservice_network

    cache:
        container_name: microservice_cache
        image: redis:latest
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: always
        volumes:
            - ./.docker/dev/microservice_cache/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6357:6379"
        networks:
            - microservice_network

    db:
        container_name: microservice_db
        image: postgres:13
        env_file: .docker/dev/microservice_db/postgres/.env
        volumes:
            - ./.docker/dev/microservice_db/postgres/data:/var/lib/postgresql/data
        ports:
            - "5457:5432"
        networks:
            - microservice_network

    testing:
        container_name: microservice_db_testing
        image: postgres:13
        env_file: .docker/dev/microservice_db_testing/postgres/.env
        ports:
            - "5458:5432"
        networks:
            - microservice_network

networks:
    microservice_network:
        driver: bridge
